name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install Dependencies
      run: npm install
    - name: Print debug information (optional)
      run: cat package.json
    - name: Start Server
      run: npm start &
    - name: Wait for server to be up
      run: npx wait-on http://localhost:5173
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        start: npm start
        wait-on: 'http://localhost:5173'
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-videos
        path: cypress/videos
